pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // colorpicker is only published on JitPack
        maven { url = 'https://jitpack.io' }
    }
}

rootProject.name = 'Pedometer'
include ':eazegraph'
